"""One-time editorial source. Never overwrite edited data without --force."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Each row: definition, hook, front question, example, application, contrast ID,
# distinction, scene EN, alternative VI, visible evidence, forbidden misconception.
ROWS = [
('Chia vật thành những phần độc lập, tháo lắp được hoặc nhỏ hơn để thuận tiện xử lý.', 'Chia nhỏ để dễ xử lý', 'Làm sao đưa chiếc kệ qua cửa hẹp mà vẫn giữ đủ công năng sử dụng?', 'Kệ rộng được tháo thành ba mô-đun đứng. Từng mô-đun lọt cửa rồi ghép lại thành kệ.', 'Phần nào trong việc của bạn có thể làm thành mô-đun độc lập?', 2, '01 chia thành phần; 02 lấy riêng phần cần hoặc gây phiền.', 'Two stacked scenes: a wide cabinet made of three side-by-side vertical modules cannot pass a doorway; then three detached intact modules individually fit through the same doorway. Keep scale fixed and show matching connectors.', 'Ống nước dài khó chở; chia thành đoạn có khớp nối để vận chuyển rồi lắp lại.', 'Intact detachable narrow modules; identical doorway; matching connectors', 'Broken furniture; modules stacked vertically instead of side-by-side; wider doorway'),
('Lấy riêng phần cần thiết hoặc đưa phần gây phiền ra khỏi đối tượng hay khu vực đang dùng.', 'Lấy đúng phần cần', 'Làm sao dùng khí nén ở bàn làm việc mà không phải chịu tiếng máy ngay cạnh?', 'Máy nén ồn đặt trong phòng riêng. Ống dẫn đưa khí đến bàn, tách nguồn ồn khỏi người dùng.', 'Bạn chỉ cần tác dụng nào, còn bộ phận nào có thể đặt xa?', 1, '02 tách nguồn gây phiền; 01 chú trọng chia thành phần độc lập.', 'One cutaway workshop: orange air compressor in a separate enclosure at left; one continuous teal air hose passes through wall to a handheld air tool on a quiet workbench at right. No person.', 'Ấm trà có giỏ lọc; nhấc riêng bã ra khi trà đủ đậm để không ngâm tiếp.', 'Separate compressor room; continuous hose; tool remains usable', 'Splitting compressor into pieces; disconnected hose'),
('Cho từng vùng tính chất hoặc điều kiện riêng, phù hợp công việc của vùng đó thay vì làm đồng loạt.', 'Mỗi vùng làm đúng việc', 'Làm sao cùng một chiếc găng vừa dễ cử động vừa bám chắc vào dụng cụ?', 'Găng có lòng bàn tay nhám để bám, mu tay mỏng để thoáng. Hai vùng đáp ứng hai nhu cầu.', 'Vùng nào cần tính chất khác để làm tốt nhiệm vụ riêng?', 40, '03 nhấn mạnh từng vùng; 40 nhấn mạnh vật liệu phối hợp.', 'Single large work glove with clearly textured orange gripping palm and thin teal breathable back shown in two adjacent views of the same glove. Keep fingertips flexible.', 'Dao có lưỡi cứng để cắt và cán nhám để cầm chắc, mỗi vùng phục vụ việc riêng.', 'Distinct functional palm and back zones', 'Uniform texture across glove; random decorative color patches'),
('Giảm tính đối xứng hoặc tăng độ bất đối xứng để hình dạng phù hợp hơn với điều kiện sử dụng.', 'Lệch có chủ đích', 'Làm sao đầu cắm tự ngăn người dùng cắm ngược mà không cần đọc hướng dẫn?', 'Đầu cắm có tiết diện hình chữ D. Ổ tương ứng chỉ nhận đúng chiều, tránh nối nhầm.', 'Bạn có thể đổi hình dạng nào để thao tác đúng trở nên tự nhiên?', 3, '04 đổi tính đối xứng; 03 phân vùng theo chức năng.', 'Close-up of an unplugged D-shaped keyed connector beside matching D-shaped socket; flat side at top and curved lower side on both. One correct alignment evident. No electrical pins complexity.', 'Bình rót có vòi lệch một bên để dòng nước tập trung và dễ hướng vào cốc.', 'Matching asymmetric D profiles', 'Symmetric circular connector; random unmatched shapes'),
('Đưa các đối tượng hoặc thao tác tương tự, kế cận lại gần nhau trong không gian hoặc thời gian.', 'Gom việc để cùng làm', 'Làm sao tạo nhiều lỗ trên tấm gỗ trong một lần đặt và giữ phôi?', 'Ba mũi khoan cùng gắn trên một đầu máy, khoan ba vị trí đồng thời khi phôi đã cố định.', 'Những thao tác lặp nào có thể thực hiện chung một lượt?', 6, '05 gom nhiều phần cùng làm; 06 một phần làm nhiều chức năng.', 'Bench drill with three identical parallel vertical drill bits on a shared head over one clamped wooden panel, three matching holes, equal spacing, machine static and no hands.', 'Kẹp nhiều tờ giấy thành một tập rồi bấm lỗ chung để các lỗ trùng nhau.', 'Three drill bits; shared head; one clamped panel', 'One drill bit changing functions; loose unsafe workpiece'),
('Cho một đối tượng đảm nhiệm nhiều chức năng để giảm nhu cầu dùng những đối tượng riêng biệt khác.', 'Một vật, nhiều việc', 'Làm sao chiếc nắp hộp vẫn hữu ích khi bạn đã mở hộp để chuẩn bị thức ăn?', 'Nắp hộp có mặt phẳng phù hợp làm thớt. Cùng một nắp vừa đóng hộp vừa đỡ thực phẩm khi cắt.', 'Bộ phận nào có thể nhận thêm chức năng để bớt một dụng cụ?', 5, '06 một vật kiêm nhiệm; 05 kết hợp nhiều vật hoặc thao tác.', 'Two scenes of the same rigid orange food container lid: fitted on teal food box; then removed flat on table as cutting board with a few vegetable slices and a resting knife.', 'Ghế đẩu có khoang rỗng dùng cất đồ, cùng một vật vừa ngồi vừa chứa.', 'Same lid recognizable in both uses', 'Separate cutting board; many unrelated attachments'),
('Đặt vật trong vật khác hoặc cho một phần đi xuyên khoảng rỗng của phần khác để dùng không gian hiệu quả.', 'Gọn nhờ chứa trong', 'Làm sao cất cả bộ bát mà chúng chỉ chiếm gần bằng chỗ của chiếc lớn nhất?', 'Bát nhỏ nằm trong bát lớn theo thứ tự kích cỡ. Bộ bát dùng chung khoảng không khi cất.', 'Khoảng rỗng nào có thể chứa một phần khác khi chưa sử dụng?', 17, '07 tận dụng bên trong; 17 mở thêm chiều hoặc tầng bố trí.', 'Three simple bowls of graduated diameter shown separated on left and nested neatly on right; a cutaway on nested set makes all three rims visible. Same bowls and scale.', 'Ống kính có các ống lồng nhau, kéo dài khi dùng và thu gọn khi cất.', 'Three rims visible within largest bowl', 'Stacked bowls without nesting; disappearing smallest bowl'),
('Bù trọng lượng bằng lực nâng của vật khác hoặc tương tác với môi trường để giảm sức nâng cần thiết.', 'Mượn lực để đỡ nặng', 'Làm sao giữ đầu ống nổi trên mặt nước mà không phải treo nó bằng dây từ bờ?', 'Phao ôm đầu ống hút, tạo lực nổi nâng cụm ống. Đầu ống theo mặt nước khi mực nước đổi.', 'Bạn có thể tận dụng lực nổi hoặc lực nâng sẵn có ở đâu?', 12, '08 bù trọng lượng bằng lực; 12 giảm nhu cầu đổi cao độ.', 'Cutaway calm water with a teal intake hose end supported at surface by an orange buoyant ring float; hose enters from shore, intake just below waterline; water displaced by float visible.', 'Cửa nâng dùng đối trọng nối qua ròng rọc để giảm lực người kéo.', 'Float partly submerged; hose supported by float', 'Levitation; float fully above water; unsupported hose'),
('Tạo trước tác động ngược với tác động bất lợi dự kiến; có thể đặt ứng suất trước để đối lại ứng suất khi làm việc.', 'Đối lại từ trước', 'Làm sao chuẩn bị dầm trước khi chịu tải để giảm nguy cơ nứt ở phía dưới?', 'Cáp căng truyền lực nén trước vào dầm. Khi tải gây kéo ở đáy, phần nén sẵn giúp giảm kéo.', 'Tác động bất lợi nào có thể được bù ngược ngay từ đầu?', 10, '09 tạo tác động đối nghịch; 10 làm trước việc cần làm.', 'Two stacked isolated orthographic beam bodies, identical geometry, with straight orange steel tendon below center and end anchorage plates. Lower beam rests on two simple supports. Blank background, no forces, arrows, cracks, text or curvature. Python will draw stress directions and load.', 'Kéo căng nan hoa trước khi bánh xe chịu tải để các nan vẫn duy trì lực căng.', 'Straight tendon; anchorage at both ends; same beam geometry', 'AI force arrows; bent tendon; upward external load; claimed design dimensions'),
('Làm sẵn toàn bộ hoặc một phần việc cần làm; sắp xếp đối tượng ở vị trí thuận lợi trước thời điểm sử dụng.', 'Chuẩn bị đúng việc trước', 'Làm sao mỗi lần đóng đơn hàng bạn không phải đo lại từng đoạn băng dính?', 'Các đoạn băng dính được cắt và đặt sẵn trên giá. Khi đóng hộp, chỉ lấy đoạn đã chuẩn bị.', 'Công đoạn nào có thể làm trước để thời điểm chính bớt chờ?', 9, '10 làm sẵn việc hữu ích; 09 tạo trước tác động đối nghịch.', 'Packing workbench: simple dispenser rack holds several pre-cut equal strips of orange tape, next to teal parcel ready for sealing; one strip positioned across seam. Clearly show prepared strips.', 'Chia sẵn nguyên liệu theo từng mẻ trước giờ nấu để lúc nấu không phải cân lại.', 'Several pre-cut strips ready on rack; parcel seam', 'Emergency spare tape; opposing stress'),
('Chuẩn bị phương tiện bảo vệ hoặc ứng cứu trước để giảm thiệt hại nếu đối tượng hoạt động không đáng tin cậy.', 'Có đường lui từ trước', 'Làm sao người đang sửa mái vẫn được giữ lại nếu bước hụt khỏi chỗ đứng?', 'Dây chống rơi đã nối đai người với điểm neo. Khi trượt chân, hệ giữ người để hạn chế rơi.', 'Nếu bước này thất bại, phương tiện ứng cứu nào phải có sẵn?', 10, '11 dành cho tình huống sự cố; 10 chuẩn bị hoạt động bình thường.', 'Conceptual small roof maintenance scene: worker safely standing, wearing harness connected by visibly continuous slack safety tether to structural anchor above. No fall in progress. Simple helmet, few details.', 'Đèn thoát hiểm có nguồn dự phòng để vẫn sáng khi mất điện lưới.', 'Harness; continuous tether; structural anchor', 'Tether tied to loose tile; fall without protection; instructional rigging detail'),
('Đổi điều kiện thao tác để đối tượng không cần được nâng lên hay hạ xuống trong quá trình làm việc.', 'Giữ cùng cao độ', 'Làm sao chuyển thùng giữa hai bàn làm việc mà người dùng không phải nhấc nó lên?', 'Hai mặt bàn và cầu nối cùng cao độ. Thùng trượt ngang giữa các trạm, giảm việc nâng hạ.', 'Bạn có thể đưa các điểm giao nhận về cùng cao độ không?', 8, '12 loại nhu cầu nâng hạ; 08 dùng lực để bù trọng lượng.', 'Orthographic front view of two workbenches with roller tops and a short connecting roller bridge, all perfectly at same height. Orange box straddles bridge, grey ghost previous position on left. Ground baseline visible.', 'Xe đẩy nhận hàng có sàn ngang mặt bàn để chuyển khay sang mà không nâng.', 'Exactly aligned tops; supported bridge; box bottom at common height', 'Ramp; staircase; floating box; lower destination'),
('Thử đảo chiều tác động, đổi phần chuyển động thành đứng yên hoặc lật đối tượng để tìm cách giải khác.', 'Đảo vai để mở cách', 'Làm sao rửa mặt trong chiếc cốc bằng chổi mà bàn tay không phải xoay chổi liên tục?', 'Chổi cố định hướng lên; người dùng úp cốc và xoay cốc quanh chổi. Vai chuyển động được đổi lại.', 'Nếu giữ dụng cụ đứng yên và cho vật chuyển động thì sao?', 15, '13 đảo vai tác động; 15 cho đặc tính thay đổi theo điều kiện.', 'Sink countertop with fixed upright brush on suction base; transparent cup inverted over brush, simple hand holding cup outside. Keep brush base anchored and cup recognizable.', 'Máy chạy bộ đưa băng tải chạy dưới chân để người đi vẫn ở một vị trí.', 'Fixed brush base; inverted cup around brush', 'Both brush and cup loose; cup resting beside brush'),
('Dùng đường cong, mặt cầu, con lăn hoặc chuyển động quay thay cho hình thẳng, mặt phẳng hay chuyển động tịnh tiến.', 'Đổi trượt thành lăn', 'Làm sao chuyển chiếc hòm nặng qua sàn mà không phải kéo đáy hòm trượt trực tiếp?', 'Các con lăn nằm dưới hòm, biến tiếp xúc trượt thành lăn. Hòm tiến đi dễ hơn trên nền phù hợp.', 'Tiếp xúc trượt nào có thể đổi thành lăn trong việc của bạn?', 28, '14 vẫn dùng cơ cấu cơ học; 28 thay cách tác động cơ học.', 'Low perspective wooden crate supported on three round teal cylindrical rollers on level floor. Front roller circular end prominently visible; no wheels attached to crate.', 'Mái vòm phân bố tải nhờ hình cong thay cho mặt mái phẳng trong một kết cấu phù hợp.', 'Round roller ends; contact supporting crate', 'Square rollers; floating crate; magnet suspension'),
('Cho hình dạng, vị trí hoặc đặc tính thay đổi theo từng điều kiện làm việc, thay vì giữ cứng một trạng thái.', 'Đổi theo lúc cần', 'Làm sao một chiếc đèn vẫn rọi đúng chỗ khi bạn đổi vị trí cuốn sách trên bàn?', 'Tay đèn có khớp xoay để đưa chụp sáng đến vị trí cần. Các phần dịch chuyển tương đối với nhau.', 'Đặc tính nào cần điều chỉnh theo từng giai đoạn sử dụng?', 1, '15 thay đổi khi dùng; 01 chú trọng chia phần để thao tác.', 'Two ghosted positions of same articulated desk lamp, solid teal arms joined by orange pivots; light shade moved above two locations of a book. One base stays fixed.', 'Ghế có mặt ngồi chỉnh cao thấp để phù hợp từng người và từng bàn.', 'Pivot joints; same fixed base; two reachable positions', 'Two separate lamps; detached broken arms'),
('Khi khó đạt đúng mức yêu cầu, thử làm ít hơn hoặc nhiều hơn một chút để bài toán dễ xử lý.', 'Chấp nhận lệch một chút', 'Làm sao lắp tấm đệm vừa chiếc khay khi rất khó cắt đúng kích thước ngay lần đầu?', 'Cắt tấm đệm dư viền, đặt vào khay rồi tỉa phần thừa. Chấp nhận dư để đạt độ vừa sau cùng.', 'Có thể cho phép dư hoặc thiếu ở bước nào rồi xử lý tiếp?', 10, '16 thay mức đạt được; 10 đổi thời điểm làm một việc.', 'Three sequential small panels: oversized orange foam sheet above teal tray; sheet laid across tray with narrow excess border; trimmed sheet fitting inside tray with offcut visible. No measurement labels.', 'Rót gần đầy bằng dòng lớn rồi thêm từng ít để đạt mức mong muốn.', 'Excess margin then removed; same tray size', 'Exactly fitted from first step; cutting tray instead of sheet'),
('Tận dụng chiều không gian khác, nhiều tầng, mặt sau hoặc đổi hướng đặt vật để vượt giới hạn bố trí hiện tại.', 'Mở thêm một chiều', 'Làm sao tăng chỗ phơi khăn trong căn phòng nhỏ mà không chiếm thêm diện tích sàn?', 'Giá phơi nhiều tầng đưa khăn lên các độ cao khác nhau. Diện tích sàn giữ nguyên nhưng thêm chỗ treo.', 'Bạn có thể dùng chiều cao hoặc mặt sau nào còn bỏ trống?', 7, '17 mở chiều bố trí; 07 đặt một vật trong khoảng rỗng vật khác.', 'Side-by-side comparison: one-level towel rack and three-level tall towel rack with identical footprint, towels spaced to hang without overlap. Floor footprint outlined in same pale teal.', 'Bảng thông báo dùng cả hai mặt để thêm nội dung trong cùng diện tích treo.', 'Same footprint; clearly separate usable levels', 'Bigger floor area; tightly packed wet towels touching'),
('Dùng rung động cơ học, điều chỉnh tần số hoặc khai thác cộng hưởng để tạo tác dụng hữu ích lên đối tượng.', 'Rung để tạo tác dụng', 'Làm sao hạt đang mắc trên mặt sàng tiếp tục đi qua lỗ mà không cần gạt từng hạt?', 'Bộ rung làm mặt sàng dao động, giúp hạt dịch chuyển và lọt lỗ. Tác dụng đến từ rung cơ học.', 'Vật liệu nào có thể được xử lý tốt hơn bằng dao động?', 19, '18 là rung cơ học; 19 là nhịp tác động, không nhất thiết rung.', 'Close-up tilted sieve tray on springs with grains above and falling through holes into bin; tiny offset ghost outlines of tray imply mechanical oscillation; no sound icons.', 'Bàn rung giúp vật liệu hạt sắp xếp chặt hơn trong khuôn phù hợp.', 'Springs; vibrating tray ghost outlines; grains through holes', 'Only flashing lamp; continuous rigid stationary sieve'),
('Chuyển tác động liên tục thành từng đợt, đổi chu kỳ hoặc dùng khoảng nghỉ giữa các đợt cho việc khác.', 'Có nhịp, có khoảng nghỉ', 'Làm sao tưới đủ nước mà đất có thời gian thấm giữa những lần được cấp thêm nước?', 'Van cấp nước theo từng đợt xen khoảng nghỉ. Nước có thời gian thấm trước khi đợt tiếp theo bắt đầu.', 'Khoảng nghỉ nào giúp quá trình của bạn vận hành tốt hơn?', 20, '19 chủ ý ngắt nhịp; 20 loại khoảng ngừng không hữu ích.', 'Three panels of same plant and drip emitter: water dripping; stopped emitter with water soaking into soil; dripping again. Same soil cutaway and pot, no controller or sensor.', 'Đèn cảnh báo nháy theo nhịp để dễ nhận thấy mà không cần phát sáng liên tục.', 'On-off-on water delivery; infiltration during pause', 'Soil moisture sensor feedback; vibrating pot'),
('Duy trì phần việc hữu ích, tận dụng cả các hành trình và giảm thời gian chạy không tải trong quá trình.', 'Đừng để lượt về trống', 'Làm sao đầu in vẫn tạo ra nội dung khi quay trở lại phía bên kia trang giấy?', 'Đầu in phun in cả lượt đi lẫn lượt về. Hành trình quay lại cũng tạo nét thay vì chỉ chạy không.', 'Lượt về hoặc thời gian chờ nào có thể tạo thêm giá trị?', 19, '20 bỏ lượt chạy rỗng; 19 có thể chủ ý tạo khoảng nghỉ.', 'Two stacked closeups of same printer carriage over paper: carriage at left with freshly printed teal swath behind toward right; then carriage at right with next orange swath behind toward left. Python adds direction arrows.', 'Băng chuyền đưa khay qua các trạm liên tiếp để công đoạn chính giảm thời gian chờ.', 'Ink deposited on both passes; same carriage and paper', 'Return pass with no ink; two unrelated printers'),
('Đưa công đoạn bất lợi qua thật nhanh để tác hại chưa kịp phát triển đáng kể trong khoảng thời gian tiếp xúc.', 'Qua nhanh trước khi hại', 'Làm sao cắt màng nhựa bằng nhiệt mà vùng quanh đường cắt ít bị biến dạng lan rộng?', 'Lưỡi nóng đi nhanh qua màng, rút ngắn thời gian truyền nhiệt ra vùng lân cận. Cần thử chế độ phù hợp.', 'Công đoạn nào gây hại chủ yếu vì tiếp xúc kéo dài?', 19, '21 rút ngắn lần tác động; 19 điều chỉnh nhịp lặp lại.', 'Conceptual close-up of guarded hot cutting blade rapidly crossing a thin teal plastic film; narrow orange heat zone limited to cut edge, surrounding film flat. No operator or temperature values.', 'Cắt nhanh một khối vật liệu mềm để giảm thời gian nó bị kéo biến dạng theo dụng cụ.', 'Narrow heat-affected strip; film remains flat', 'Broad melting puddle; implied universal safe cutting speed'),
('Tìm cách dùng yếu tố vốn gây hại để tạo ích lợi, hoặc biến đổi điều kiện để tác hại bị triệt tiêu.', 'Đổi vai của điều hại', 'Làm sao hơi nóng đang làm phòng máy khó chịu có thể giúp ích cho một công việc khác?', 'Nhiệt thải được dẫn qua bộ trao đổi nhiệt để làm ấm nước. Phần gây nóng phòng trở thành nguồn dùng được.', 'Tác nhân đang gây phiền nào có thể phục vụ nhu cầu khác?', 25, '22 đổi vai yếu tố có hại; 25 hệ tự làm việc phụ trợ.', 'Simple heat exchanger between warm orange machine exhaust duct and separate teal water tank coil; two fluids remain separated by metal wall. Python adds heat direction overlay.', 'Nước mưa gây đọng sân được gom vào bể tưới cây để tạo nguồn sử dụng.', 'Separate exhaust and water circuits; intervening exchanger', 'Dirty exhaust mixed directly into water; magic electricity'),
('Đưa thông tin về kết quả quay lại để điều chỉnh tác động tiếp theo; thay đổi cách phản hồi nếu cần.', 'Nhìn kết quả, chỉnh lại', 'Làm sao hệ tưới biết lúc nào nên giảm nước thay vì cứ mở van theo lịch cố định?', 'Cảm biến đo ẩm đất gửi về bộ điều khiển. Bộ điều khiển đổi độ mở van theo mức ẩm đo được.', 'Kết quả nào cần đo để điều chỉnh hành động kế tiếp?', 19, '23 dùng kết quả để chỉnh; 19 có thể chỉ lặp theo lịch.', 'Four isolated objects arranged as a square loop: top-left controller box, top-right irrigation valve, bottom-right potted plant with wet soil cutaway, bottom-left soil moisture probe. No wires, arrows, labels or screen text. Python will draw the exact closed feedback topology.', 'Phao trong bồn đổi vị trí theo mực nước và tác động van để ngừng cấp khi đầy.', 'Four separate objects in prescribed quadrants', 'AI-drawn connections; display without actuator; open-loop clock'),
('Đưa một vật hoặc quá trình trung gian vào để truyền tác động hay kết nối hai bên khó tương tác trực tiếp.', 'Qua một cầu nối', 'Làm sao gõ chỉnh vị trí tấm gỗ mà bề mặt hoàn thiện không nhận trực tiếp vết búa?', 'Một miếng gỗ đệm nằm giữa búa và phôi. Nó truyền lực gõ đồng thời phân bố tiếp xúc lên bề mặt.', 'Vật trung gian nào có thể giúp hai bên tác động phù hợp hơn?', 30, '24 là vai trò truyền tác động; 30 nhấn mạnh vỏ hoặc màng.', 'Close-up resting hammer over sacrificial orange wooden block contacting edge of finished teal wooden board. Show hammer-block-board order, no hand, board on solid bench.', 'Phễu làm trung gian dẫn nước từ bình miệng rộng vào chai cổ nhỏ.', 'Block physically between hammer and finished surface', 'Hammer hitting finished board directly; floating block'),
('Cho hệ tự thực hiện thao tác phụ trợ hoặc tận dụng tài nguyên, năng lượng sẵn có để phục vụ chính nó.', 'Dùng mình để phục vụ mình', 'Làm sao nước đang chảy qua vòi có thể tự làm đầu tưới quay mà không cần mô-tơ riêng?', 'Nước thoát qua các vòi lệch hướng tạo phản lực làm đầu tưới quay. Dòng nước kiêm việc dẫn động.', 'Năng lượng đang có trong hệ có thể làm thêm việc phụ nào?', 22, '25 hệ tự phục vụ; 22 biến yếu tố có hại thành ích lợi.', 'Top view rotating lawn sprinkler: two opposite curved arms discharge water tangentially in opposite directions, mounted on central bearing and supply hose. No electric motor or cables. Python draws rotation if needed.', 'Cửa có lò xo tích năng lượng khi mở rồi tự khép lại, không cần người kéo về.', 'Tangential jets; central bearing; water supply', 'External motor; radial jets claiming torque'),
('Dùng bản sao đơn giản hoặc hình ảnh đại diện khi làm việc với vật thật khó, đắt, dễ hỏng hoặc không sẵn có.', 'Thử trên bản sao', 'Làm sao thử nhiều cách bố trí bàn ghế mà không phải kéo đồ thật quanh phòng mỗi lần?', 'Mô hình căn phòng và bàn ghế theo cùng tỷ lệ cho phép thử bố trí. Đồ thật không cần di chuyển.', 'Bản sao nào đủ giữ thông tin cần thiết cho quyết định của bạn?', 27, '26 thay bằng đại diện; 27 dùng vật rẻ trực tiếp làm việc.', 'Architectural tabletop room model with movable miniature tables and chairs; faint full-sized room in background at deliberately different scale. Model clearly a representative scale copy, no text.', 'Ảnh chụp theo tỷ lệ giúp kiểm tra hình dáng chi tiết mà không chạm vào mẫu dễ vỡ.', 'Recognizable room model; movable miniatures; scale relationship', 'Toy unrelated to real room; random dimensional distortion'),
('Thay vật đắt bằng những vật rẻ hơn, chấp nhận giảm một số phẩm chất như tuổi thọ khi điều đó phù hợp.', 'Đủ dùng với giá thấp', 'Làm sao lót bàn khi pha màu mà không cần giữ một tấm lót đắt tiền qua nhiều lần dùng?', 'Tờ giấy lót rẻ nhận vết màu rồi được thay. Chấp nhận tuổi thọ ngắn để bớt việc bảo quản tấm đắt.', 'Phẩm chất nào có thể giảm mà vẫn đáp ứng nhu cầu thực tế?', 26, '27 vật rẻ làm việc thật; 26 bản sao đại diện cho vật gốc.', 'Artist mixing colors on disposable plain paper liner covering table, stained top sheet and small clean stack nearby; modest reusable tray comparison behind, no brand or money symbols.', 'Miếng chèn đóng gói bằng giấy dùng ngắn hạn thay phụ kiện bền đắt khi chỉ cần một chuyến.', 'Cheap paper actually protecting tabletop; replacement sheets', 'Claim that disposable is always environmentally superior; replica only'),
('Thay cách tác động cơ học bằng điện, từ, quang, âm hoặc trường thích hợp để tạo tương tác cần thiết.', 'Đổi cách tác động', 'Làm sao nhặt các chi tiết sắt nhỏ khỏi khay mà không phải kẹp từng chiếc bằng ngàm?', 'Nam châm hút đồng thời các chi tiết sắt. Lực từ thay cho cơ cấu ngàm kẹp tiếp xúc từng chi tiết.', 'Tác động cơ học nào có thể chuyển sang điện, từ hoặc quang?', 14, '28 đổi phương thức tương tác; 14 đổi hình hoặc chuyển động cơ học.', 'Large teal horseshoe magnet suspended just above a shallow tray, orange steel washers clustered at poles; no mechanical jaws. A few nonmagnetic wooden pieces remain in tray.', 'Cảm biến quang nhận biết vật đi qua thay cho cần gạt bị vật chạm trực tiếp.', 'Steel items attached at magnetic poles; no jaws', 'Wood attracted to magnet; invisible unsupported heavy objects'),
('Dùng khí hoặc chất lỏng thay bộ phận rắn để đỡ, truyền lực hoặc tạo kết cấu phù hợp với đối tượng.', 'Nhờ khí, nhờ lỏng', 'Làm sao đỡ món đồ có hình dạng không đều mà không phải chế tạo một khuôn cứng riêng?', 'Đệm chứa khí biến dạng theo đáy vật, phân bố chỗ đỡ. Phần khí chịu nén thay vai trò gối đỡ cứng.', 'Bộ phận rắn nào có thể thay bằng thể tích khí hoặc chất lỏng?', 30, '29 khí/lỏng tạo tác dụng; 30 vỏ/màng cách ly hoặc bao che.', 'Cutaway inflatable cushion supporting irregular ceramic vase base; sealed teal flexible envelope contains pale blue air cells; contact contour follows base with visible compression.', 'Bàn nâng thủy lực truyền lực qua dầu để nâng mặt bàn bằng cơ cấu thích hợp.', 'Enclosed air volume; deformed support surface', 'Solid foam pores mistaken for air bladder; empty outline only'),
('Thay kết cấu khối bằng vỏ mềm hoặc màng mỏng; dùng chúng để bao bọc và cách ly vật với môi trường.', 'Mỏng mà vẫn che được', 'Làm sao che bát thức ăn có miệng khác nhau mà không cần làm riêng một nắp cứng cho từng bát?', 'Màng mềm ôm sát miệng bát, tạo lớp che mỏng. Nó thay nắp khối và thích ứng hình dạng mép.', 'Lớp bao che nào có thể mỏng, mềm hơn mà vẫn đủ chức năng?', 29, '30 nhấn vào lớp vỏ mỏng; 29 dùng khí/lỏng để đỡ hoặc truyền lực.', 'Two bowls with different rim diameters sealed by very thin transparent stretch film clinging to rims; lifted spare corner shows flexible sheet, contents visible, no inflated chamber.', 'Áo mưa mỏng gấp gọn tạo lớp ngăn nước khi cần thay vì vỏ che cứng.', 'Thin conforming transparent film; rim contact', 'Thick rigid lid; inflated support cushion'),
('Tạo lỗ rỗng trong vật liệu hoặc thêm phần xốp; có thể dùng các lỗ ấy để chứa chất phục vụ công việc.', 'Để lỗ rỗng làm việc', 'Làm sao miếng lau giữ được dung dịch để nhả dần khi bạn ép nó lên mặt bàn?', 'Các lỗ rỗng trong miếng xốp giữ dung dịch. Khi bị ép, dung dịch thoát ra giúp làm sạch bề mặt.', 'Những lỗ rỗng nào có thể chứa hoặc dẫn một chất hữu ích?', 29, '31 có mạng lỗ trong vật liệu; 29 dùng thể tích khí/lỏng làm kết cấu.', 'Large cutaway porous sponge above wet table, interconnected visible pores holding teal liquid; slight compression by flat plate releases a few droplets beneath. Orange sponge skeleton.', 'Chậu đất nung xốp cho nước thấm chậm qua thành để cấp ẩm cho đất quanh chậu.', 'Open connected pores; liquid in pores; droplets under compression', 'Single sealed air bladder; solid block with painted dots'),
('Đổi màu, độ trong suốt hoặc đặc tính phát sáng để làm trạng thái hay thông tin cần quan sát dễ nhận ra.', 'Cho trạng thái hiện ra', 'Làm sao nhận ra vùng tay cầm còn nóng mà không phải chạm tay vào để kiểm tra?', 'Miếng chỉ thị đổi màu theo nhiệt độ trên tay cầm. Màu làm trạng thái khó thấy trở nên dễ quan sát.', 'Trạng thái nào cần biến thành dấu hiệu nhìn được ngay?', 35, '32 tập trung tín hiệu nhìn; 35 thay thông số để đổi tác dụng.', 'Two identical kettle handles with small thermochromic patches: warm handle orange patch and steam from kettle, cooled handle teal patch and no steam. No digits, thermometers or hands.', 'Cửa sổ trong trên hộp cho thấy mức vật liệu bên trong mà không cần mở nắp.', 'Same patch changes color; contextual hot and cool states', 'Only decorative color variation; hands touching hot part'),
('Chọn vật tương tác có cùng vật liệu hoặc tính chất tương hợp với đối tượng chính để tránh khác biệt gây bất lợi.', 'Tương hợp để cùng làm', 'Làm sao miếng vá giãn và co cùng chiếc áo khi người mặc vận động rồi giặt áo?', 'Miếng vá dùng cùng loại vải với áo. Hai phần có đặc tính gần nhau, giảm chênh lệch khi co giãn.', 'Vật tiếp xúc nào nên có tính chất gần giống vật chính?', 40, '33 tìm sự tương đồng; 40 phối hợp vật liệu khác nhau.', 'Close-up teal woven shirt fabric and matching same-weave patch stitched on elbow; adjacent small swatch clearly cut from same fabric roll. Orange stitching, cloth texture visible.', 'Que hàn chọn phù hợp vật liệu chi tiết để mối nối có tính chất tương hợp.', 'Same weave and material on patch and base', 'Metal patch on cloth; contrasting material layers'),
('Cho phần đã hoàn tất nhiệm vụ tự mất đi hoặc biến đổi; cũng có thể phục hồi phần hao hụt ngay khi làm việc.', 'Xong việc thì rời đi', 'Làm sao lấy phần chống đỡ ra khỏi chi tiết in rỗng khi dụng cụ không luồn vào được?', 'Giá đỡ hòa tan giữ hình trong lúc in. Sau đó nó tan trong dung môi phù hợp, để lại khoang rỗng.', 'Phần tạm nào có thể tự biến mất sau khi hoàn thành nhiệm vụ?', 25, '34 phần hết nhiệm vụ mất đi; 25 hệ tự thực hiện việc phụ.', 'Two panels: teal hollow 3D printed arch with orange soluble supports filling cavity; same arch immersed in transparent bath, supports partly dissolving and open cavity emerging. Outer teal arch stays intact.', 'Lưỡi dao tự mài giữ cạnh sắc nhờ các lớp mòn khác nhau trong khi sử dụng.', 'Temporary supports disappearing; final part intact', 'Whole object dissolving; cutting main part away'),
('Đổi trạng thái, nồng độ, độ dẻo, nhiệt độ hoặc thông số hóa lý khác để vật phù hợp hơn với công việc.', 'Đổi thông số, đổi cách dùng', 'Làm sao giảm thể tích hàng cần chở mà người dùng vẫn pha được đủ dung dịch để sử dụng?', 'Dung dịch được làm đậm đặc để chở trong chai nhỏ. Tại nơi dùng, thêm nước đến nồng độ cần thiết.', 'Thông số nào có thể thay đổi giữa lúc vận chuyển và lúc sử dụng?', 36, '35 đổi nồng độ ở đây; 36 tận dụng hiệu ứng lúc chuyển pha.', 'Small bottle of dark teal concentrate beside larger transparent mixing jug with pale teal diluted solution; clear water pitcher between them; same liquid family, no measurement scales or text.', 'Vật liệu được làm mềm vừa đủ trước khi uốn rồi trở lại trạng thái dùng phù hợp.', 'Concentrate small volume; diluted large volume; added water', 'Phase-change ice; multiplying liquid with no added water'),
('Tận dụng hiệu ứng xuất hiện trong quá trình chuyển pha, chẳng hạn thu nhiệt, tỏa nhiệt hoặc thay đổi thể tích.', 'Dùng hiệu ứng lúc đổi pha', 'Vì sao túi giữ mát vẫn nhận thêm nhiệt trong lúc phần lõi rắn của nó đang tan?', 'Lõi trong túi hấp thu nhiệt khi nóng chảy. Nhiệt nhận vào gắn với quá trình tan, giúp giữ mát đồ cạnh túi.', 'Hiệu ứng chuyển pha nào có thể hỗ trợ vấn đề nhiệt của bạn?', 35, '36 khai thác nhiệt khi tan; 35 rộng hơn về thay thông số.', 'Cutaway sealed cold pack beside small lunchbox: pack visibly contains both solid pale teal chunks and teal liquid of the SAME material, partly melted. No arrows; Python draws heat entering pack from outside.', 'Sáp chuyển pha trong hộp đệm nhiệt thu nhiệt khi tan rồi tỏa nhiệt khi đông lại.', 'Coexisting solid and liquid inside sealed pack', 'Heat arrow out of melting pack; only blue cold color; boiling liquid'),
('Dùng sự nở hoặc co do nhiệt, hay độ nở khác nhau của các vật liệu, để tạo thay đổi có ích.', 'Nhiệt đổi kích thước', 'Làm sao lắp vòng kim loại vừa chặt quanh trục khi ở nhiệt độ thường rất khó đưa vào?', 'Vòng được làm ấm cho lỗ nở ra, lắp lên trục rồi để nguội. Vòng co lại giúp tạo mối ghép chặt.', 'Sự nở hoặc co nào có thể hỗ trợ lắp ghép trong hệ của bạn?', 36, '37 vật còn cùng pha; 36 có quá trình chuyển pha.', 'Three panels: orange metal ring with small gap to teal shaft; warmer slightly expanded ring sliding over same shaft; cooled ring snug around shaft. No flames, arrows, temperature values, melting or dimensional labels.', 'Thanh lưỡng kim cong khi nóng do hai lớp nở khác nhau, dùng để tác động công tắc.', 'Hole expands along with ring; solid metal throughout', 'Heating makes hole smaller; molten ring'),
('Tăng khả năng oxy hóa của môi trường, chẳng hạn dùng khí giàu oxy, để thúc đẩy quá trình cần oxy hóa.', 'Tăng sức oxy hóa', 'Làm sao hỗ trợ quá trình đốt trong lò khi lượng oxy của luồng khí cấp đang là giới hạn?', 'Luồng khí cấp được làm giàu oxy, hỗ trợ quá trình cháy. Đây là sơ đồ khái niệm của thiết bị công nghiệp.', 'Quá trình nào thực sự cần tăng khả năng oxy hóa của môi trường?', 39, '38 tăng khả năng oxy hóa; 39 hạn chế tương tác bằng môi trường trơ.', 'Conceptual sealed industrial furnace shown in simple cutaway, two inlet gas streams one ordinary air pale teal and one oxygen-rich orange mixed before burner; flame contained inside guarded furnace. No gas cylinders, recipes or numeric settings.', 'Thiết bị xử lý nước dùng chất oxy hóa phù hợp để biến đổi tạp chất trong hệ kín.', 'Enclosed controlled furnace; enriched oxidizing feed', 'DIY torch; open oxygen bottle; inert gas shown as oxidizer'),
('Dùng môi trường ít phản ứng hoặc chân không để giảm tương tác bất lợi giữa vật và môi trường thông thường.', 'Bớt phản ứng không cần', 'Làm sao bảo vệ vùng kim loại đang hàn khỏi phản ứng không mong muốn với không khí xung quanh?', 'Khí argon bao quanh vùng hàn, hạn chế tiếp xúc không khí. Môi trường ít phản ứng giúp bảo vệ mối hàn.', 'Tương tác môi trường nào cần giảm bằng môi trường trơ hoặc chân không?', 38, '39 giảm phản ứng môi trường; 38 tăng khả năng oxy hóa.', 'Conceptual closeup welding torch nozzle surrounded by visible pale teal shielding gas envelope over small weld pool; metal plates on workbench; surrounding air outside envelope. No worker or technical settings.', 'Bao bì được nạp khí nitơ để giảm oxy tiếp xúc với thực phẩm nhạy oxy hóa.', 'Shielding gas envelope covers weld pool', 'Oxygen feed labeled inert; unshielded arc; tutorial settings'),
('Phối hợp nhiều vật liệu thành một kết cấu để khai thác các tính chất bổ sung mà một vật liệu riêng khó đáp ứng.', 'Khác nhau để bổ trợ', 'Làm sao một tấm vách vừa nhẹ vừa chống uốn tốt mà không dùng toàn bộ kim loại đặc?', 'Tấm sandwich có hai lớp mặt cứng gắn với lõi xốp nhẹ. Mặt và lõi cùng làm việc khi tấm chịu uốn.', 'Những vật liệu nào có thể bổ sung tính chất cho nhau trong sản phẩm?', 3, '40 phối hợp vật liệu; 03 chú trọng tính chất riêng từng vùng.', 'Large clean cutaway of one BONDED sandwich panel: thin orange aluminum top and bottom face sheets firmly joined to thicker teal closed-cell polymer foam core, continuous flush edges; small enlarged cutaway shows core pores. No detached floating layers.', 'Sợi thủy tinh nằm trong nền nhựa tạo vật liệu vừa dễ tạo hình vừa được gia cường.', 'Two stiff thin face sheets bonded to different lightweight core', 'Loose stack; identical layers; steel reinforcing bars instead of foam'),
]

STYLE = ('Use case: scientific-educational. Create one square editorial illustration for an adult TRIZ learning card. '
         'Crisp vector-like shapes, dark navy outlines (#163447), warm ivory background (#F7F3E9), restrained teal (#268B88) '
         'and orange (#E99049), subtle shadows, uncluttered composition, all essential objects within central 84 percent. ')

def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--force', action='store_true')
    args = parser.parse_args()
    dest = ROOT / 'data/principles.json'
    if dest.exists() and not args.force:
        raise SystemExit('Data exists. Edit data/principles.json directly; --force explicitly reseeds.')
    vi = json.loads((ROOT / 'src/Data/40principles_vi.json').read_text())
    en = json.loads((ROOT / 'data/40principles.json').read_text())
    evidence = (ROOT / 'data/evidence/noi-bo-2026-09-11.html').read_text()
    evidence_hash = hashlib.sha256(evidence.encode()).hexdigest()
    terms, cards = [], []
    for p, e, row in zip(vi, en, ROWS, strict=True):
        i = p['id']
        assert i == e['id'] and p['title'] in evidence
        name = p['title'].removeprefix('Nguyên tắc ')
        definition, hook, question, example, application, other, distinction, scene, alternative, show, avoid = row
        section = f'Danh sách bài giảng / nguyên tắc {i:02}'
        source = {'url':'https://trizvietnam.com/vi/noi-bo', 'section':section}
        terms.append({'id':i, 'original_name_vi':p['title'], 'display_name_vi':name, 'name_en':e['title'], 'aliases_vi':[],
                      'sources':[source], 'verification_status':'verified_designated_web_source', 'verified_at':'2026-09-11',
                      'evidence_path':'data/evidence/noi-bo-2026-09-11.html', 'evidence_sha256':evidence_hash,
                      'book_comparison_status':'not_independently_checked', 'display_rule':'remove_exact_prefix_only'})
        prompt = STYLE + '\nTeaching objective: ' + e['title'] + '.\nScene: ' + scene + '\nMust show: ' + show + '.\nAvoid: ' + avoid + '.\nNo text, letters, numbers, labels, logos, watermarks, card borders or arrows. Python supplies precise overlays.\n'
        if i == 1:
            prompt = (ROOT/'prompts/01.txt').read_text()
        cards.append({'id':i, 'name_vi':name, 'name_en':e['title'], 'aliases_vi':[], 'definition_vi':definition,
                      'memory_hook_vi':hook, 'front_question_vi':question, 'example_vi':example,
                      'mechanism_vi':example.split('. ')[0] + '.', 'benefit_vi':example.split('. ')[-1],
                      'application_question_vi':application, 'confusable_with':[other], 'distinction_vi':distinction,
                      'source_refs':[source, {'url':'https://the-trizjournal.com/40-inventive-principles-examples/', 'section':f'Principle {i}'},
                                     {'url':f'https://trizvietnam.com/vi/principles/{i}', 'section':f'Nguyên tắc {i}'}],
                      'visual_brief':{'scene':scene, 'layout':'controlled_diagram' if i in (9,23,36) else ('sequence' if i in (16,19,37) else 'editorial'),
                                      'alternatives':[{'scene_vi':example, 'assessment_vi':'Cơ chế có dấu hiệu vật lý trực tiếp trong must_show, đọc được trong một vùng hình vuông.'},
                                                      {'scene_vi':alternative, 'assessment_vi':'Hợp cơ chế nhưng cần thêm bối cảnh hoặc chi tiết nhỏ để phân biệt ở khổ thẻ.'}],
                                      'selection_reason_vi':f'Chọn cảnh thứ nhất; bằng chứng cần nhìn: {show}.',
                                      'must_show':show.split('; '), 'must_avoid':avoid.split('; '),
                                      'scope_note':'Minh họa một ứng dụng cụ thể; không bao quát mọi cách dùng nguyên tắc.'},
                      'image_prompt_en':prompt, 'overlay_spec':[], 'content_status':'editorially_reviewed'})
    # Coordinates normalized in a dedicated diagram inset, independent of AI geometry.
    cards[8]['overlay_spec'] = [{'kind':'prestress', 'stages':['Nén trước', 'Tải làm việc'], 'compression_arrows':[[0.1,0.3,0.3,0.3],[0.9,0.3,0.7,0.3]], 'load_arrow':[0.5,0.6,0.5,0.8], 'note':'Sơ đồ khái niệm; không dùng tính toán kết cấu.'}]
    cards[22]['overlay_spec'] = [{'kind':'feedback','nodes':['Điều khiển','Van','Đất','Cảm biến'], 'edges':[[0,1],[1,2],[2,3],[3,0]], 'note':'Đo ẩm → chỉnh van → đổi ẩm → đo lại.'}]
    cards[35]['overlay_spec'] = [{'kind':'heat','direction':'environment_to_pack','note':'Nhận nhiệt khi lõi đang tan.'}]
    cards[19]['overlay_spec'] = [{'kind':'passes','directions':['right','left']}]
    cards[21]['overlay_spec'] = [{'kind':'heat_recovery','direction':'waste_to_water'}]
    write_json(dest, cards)
    write_json(ROOT/'data/terminology_vi.json', terms)
    write_json(ROOT/'data/terminology_lock.json', {'sha256':hashlib.sha256((ROOT/'data/terminology_vi.json').read_bytes()).hexdigest(),
               'basis':'40 names match the user-designated web page and repository title table; not a book concordance.', 'locked_at':'2026-09-11'})
    print('Seeded and source-checked 40 cards and 40 terminology records.')

if __name__ == '__main__':
    main()
